project_id = "nkkalmyhxtuisjdjmdew"

[functions.log-security-event]
verify_jwt = false

[functions.subscribe]
verify_jwt = false

[functions.admin-invite-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false
