project_id = "nkkalmyhxtuisjdjmdew"

[functions.log-security-event]
verify_jwt = false

[functions.subscribe]
verify_jwt = false

[functions.send-hostinger-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.admin-invite-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.handle-pending-registration]
verify_jwt = false

[functions.approve-pending-user]
verify_jwt = true

[functions.convert-subscriber-to-user]
verify_jwt = true

[functions.send-password-reset-link]
verify_jwt = true
