project_id = "nkkalmyhxtuisjdjmdew"

[functions.proxy-file]
verify_jwt = false

[functions.admin-create-student]
verify_jwt = true

[functions.admin-set-professor-password]
verify_jwt = true

[functions.log-security-event]
verify_jwt = false

[functions.subscribe]
verify_jwt = false

[functions.send-hostinger-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.admin-invite-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.handle-pending-registration]
verify_jwt = false

[functions.approve-pending-user]
verify_jwt = true

[functions.convert-subscriber-to-user]
verify_jwt = true

[functions.book-appointment]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.validate-qr-checkin]
verify_jwt = true

[functions.send-class-reminders]
verify_jwt = false

[functions.create-professor]
verify_jwt = true

[functions.send-professor-reset]
verify_jwt = true

[functions.setup-professor-auth]
verify_jwt = true
