
-- First, let's add the new courses for Pillar 1: AI & Machine Learning
INSERT INTO courses (
  title, subtitle, modules, duration, diploma, feature1, feature2, icon, 
  gradient_from, gradient_to, button_text_color, floating_color1, floating_color2, 
  link_to, status, display_order
) VALUES 
-- AI & Machine Learning Engineering
(
  'AI & Machine Learning Engineering',
  'Maîtrisez l''ingénierie des systèmes d''IA et ML',
  '12 modules intensifs',
  '6 mois',
  'Certificat d''Ingénieur IA & ML',
  'Développement de modèles ML en production',
  'Architecture de systèmes d''IA scalables',
  'brain',
  'from-purple-600',
  'to-blue-600',
  'text-purple-600',
  'bg-purple-100/20',
  'bg-blue-100/10',
  '/course/ai-ml-engineering',
  'published',
  4
),
-- Business Intelligence
(
  'Business Intelligence',
  'Transformez les données en insights stratégiques',
  '10 modules pratiques',
  '4 mois',
  'Certificat Business Intelligence',
  'Tableaux de bord interactifs',
  'Analyse prédictive pour entreprises',
  'target',
  'from-blue-500',
  'to-indigo-600',
  'text-blue-500',
  'bg-blue-100/20',
  'bg-indigo-100/10',
  '/course/business-intelligence',
  'published',
  5
),
-- AI for Business
(
  'AI for Business',
  'Intégrez l''IA dans votre stratégie d''entreprise',
  '8 modules stratégiques',
  '3 mois',
  'Certificat AI Business Strategy',
  'ROI et métriques d''IA',
  'Transformation digitale par l''IA',
  'brain',
  'from-green-500',
  'to-teal-600',
  'text-green-500',
  'bg-green-100/20',
  'bg-teal-100/10',
  '/course/ai-for-business',
  'published',
  6
),
-- AI for Decision Making
(
  'AI for Decision Making',
  'Optimisez vos décisions avec l''intelligence artificielle',
  '9 modules décisionnels',
  '4 mois',
  'Certificat AI Decision Making',
  'Algorithmes de recommandation',
  'Systèmes d''aide à la décision',
  'target',
  'from-orange-500',
  'to-red-600',
  'text-orange-500',
  'bg-orange-100/20',
  'bg-red-100/10',
  '/course/ai-decision-making',
  'published',
  7
),
-- Computer Vision with OpenCV
(
  'Computer Vision with OpenCV',
  'Maîtrisez la vision par ordinateur avec OpenCV',
  '11 modules visuels',
  '5 mois',
  'Certificat Computer Vision',
  'Détection et reconnaissance d''objets',
  'Traitement d''images en temps réel',
  'brain',
  'from-purple-500',
  'to-pink-600',
  'text-purple-500',
  'bg-purple-100/20',
  'bg-pink-100/10',
  '/course/computer-vision-opencv',
  'published',
  8
),
-- Ethical AI & Governance
(
  'Ethical AI & Governance',
  'Développez une IA responsable et éthique',
  '7 modules éthiques',
  '3 mois',
  'Certificat Ethical AI',
  'Biais algorithmiques et fairness',
  'Réglementation et conformité IA',
  'shield',
  'from-gray-600',
  'to-slate-700',
  'text-gray-600',
  'bg-gray-100/20',
  'bg-slate-100/10',
  '/course/ethical-ai-governance',
  'published',
  9
),
-- Python for AI & Programming
(
  'Python for AI & Programming',
  'Programmation Python spécialisée pour l''IA',
  '10 modules Python',
  '4 mois',
  'Certificat Python AI Developer',
  'Librairies IA (TensorFlow, PyTorch)',
  'Optimisation et performance',
  'code',
  'from-yellow-500',
  'to-orange-600',
  'text-yellow-600',
  'bg-yellow-100/20',
  'bg-orange-100/10',
  '/course/python-ai-programming',
  'published',
  10
),
-- Data Science for Business
(
  'Data Science for Business',
  'Science des données appliquée aux entreprises',
  '12 modules business',
  '6 mois',
  'Certificat Data Science Business',
  'KPI et métriques business',
  'Modèles prédictifs ROI',
  'database',
  'from-teal-500',
  'to-cyan-600',
  'text-teal-500',
  'bg-teal-100/20',
  'bg-cyan-100/10',
  '/course/data-science-business',
  'published',
  11
),
-- Data Science with Scikit-learn
(
  'Data Science with Scikit-learn',
  'Maîtrisez Scikit-learn pour la data science',
  '9 modules techniques',
  '4 mois',
  'Certificat Scikit-learn Expert',
  'Machine Learning avec Scikit-learn',
  'Préprocessing et feature engineering',
  'database',
  'from-blue-600',
  'to-purple-700',
  'text-blue-600',
  'bg-blue-100/20',
  'bg-purple-100/10',
  '/course/data-science-scikit-learn',
  'published',
  12
),
-- AI Applications in Industries
(
  'AI Applications in Industries',
  'IA appliquée aux secteurs industriels',
  '10 modules sectoriels',
  '5 mois',
  'Certificat AI Industry Applications',
  'IA dans la santé, finance, retail',
  'Cas d''usage industriels concrets',
  'brain',
  'from-indigo-500',
  'to-blue-700',
  'text-indigo-500',
  'bg-indigo-100/20',
  'bg-blue-100/10',
  '/course/ai-applications-industries',
  'published',
  13
);

-- Now let's add Pillar 2: Data, Programming & Supporting Specializations
INSERT INTO courses (
  title, subtitle, modules, duration, diploma, feature1, feature2, icon, 
  gradient_from, gradient_to, button_text_color, floating_color1, floating_color2, 
  link_to, status, display_order
) VALUES 
-- Data Analysis with Microsoft Excel
(
  'Data Analysis with Microsoft Excel',
  'Analyse de données avancée avec Excel',
  '8 modules Excel',
  '3 mois',
  'Certificat Excel Data Analyst',
  'Tableaux croisés dynamiques avancés',
  'Macros et automatisation VBA',
  'database',
  'from-green-600',
  'to-emerald-700',
  'text-green-600',
  'bg-green-100/20',
  'bg-emerald-100/10',
  '/course/excel-data-analysis',
  'published',
  14
),
-- Financial Data Analysis
(
  'Financial Data Analysis',
  'Analyse financière et modélisation',
  '10 modules finance',
  '4 mois',
  'Certificat Financial Data Analyst',
  'Modèles financiers et valorisation',
  'Risk management et backtesting',
  'target',
  'from-emerald-500',
  'to-green-700',
  'text-emerald-500',
  'bg-emerald-100/20',
  'bg-green-100/10',
  '/course/financial-data-analysis',
  'published',
  15
),
-- Google Data Studio Analytics
(
  'Google Data Studio Analytics',
  'Visualisation de données avec Google Data Studio',
  '7 modules visualisation',
  '3 mois',
  'Certificat Google Data Studio',
  'Dashboards interactifs',
  'Connecteurs et sources de données',
  'database',
  'from-blue-500',
  'to-sky-600',
  'text-blue-500',
  'bg-blue-100/20',
  'bg-sky-100/10',
  '/course/google-data-studio',
  'published',
  16
),
-- Database Design & Management
(
  'Database Design & Management',
  'Conception et gestion de bases de données',
  '11 modules database',
  '5 mois',
  'Certificat Database Administrator',
  'Modélisation et normalisation',
  'Optimisation et performance',
  'database',
  'from-slate-600',
  'to-gray-700',
  'text-slate-600',
  'bg-slate-100/20',
  'bg-gray-100/10',
  '/course/database-design-management',
  'published',
  17
),
-- Advanced Python Programming
(
  'Advanced Python Programming',
  'Programmation Python avancée',
  '12 modules Python',
  '5 mois',
  'Certificat Python Advanced Developer',
  'Programmation orientée objet avancée',
  'Optimisation et multithreading',
  'code',
  'from-yellow-600',
  'to-amber-700',
  'text-yellow-600',
  'bg-yellow-100/20',
  'bg-amber-100/10',
  '/course/advanced-python-programming',
  'published',
  18
),
-- Web Development (HTML, CSS, JS)
(
  'Web Development (HTML, CSS, JS)',
  'Développement web moderne et responsive',
  '14 modules web',
  '6 mois',
  'Certificat Web Developer',
  'Frameworks modernes (React, Vue)',
  'Responsive design et UX/UI',
  'code',
  'from-orange-500',
  'to-red-600',
  'text-orange-500',
  'bg-orange-100/20',
  'bg-red-100/10',
  '/course/web-development',
  'published',
  19
),
-- Mobile App Development
(
  'Mobile App Development',
  'Développement d''applications mobiles',
  '13 modules mobile',
  '6 mois',
  'Certificat Mobile App Developer',
  'iOS et Android natif',
  'React Native et Flutter',
  'code',
  'from-purple-600',
  'to-violet-700',
  'text-purple-600',
  'bg-purple-100/20',
  'bg-violet-100/10',
  '/course/mobile-app-development',
  'published',
  20
),
-- Cloud Computing (AWS, Azure)
(
  'Cloud Computing (AWS, Azure)',
  'Architecture cloud et DevOps',
  '15 modules cloud',
  '7 mois',
  'Certificat Cloud Architect',
  'AWS et Azure certifications',
  'Kubernetes et microservices',
  'cloud',
  'from-sky-500',
  'to-blue-700',
  'text-sky-500',
  'bg-sky-100/20',
  'bg-blue-100/10',
  '/course/cloud-computing',
  'published',
  21
),
-- Internet of Things (IoT)
(
  'Internet of Things (IoT)',
  'Connectez le monde physique au digital',
  '10 modules IoT',
  '5 mois',
  'Certificat IoT Developer',
  'Capteurs et microcontrôleurs',
  'Plateformes IoT et protocols',
  'target',
  'from-teal-600',
  'to-cyan-700',
  'text-teal-600',
  'bg-teal-100/20',
  'bg-cyan-100/10',
  '/course/internet-of-things',
  'published',
  22
),
-- Blockchain & Cryptocurrency
(
  'Blockchain & Cryptocurrency',
  'Technologie blockchain et cryptomonnaies',
  '11 modules blockchain',
  '5 mois',
  'Certificat Blockchain Developer',
  'Smart contracts et DeFi',
  'Développement Web3',
  'shield',
  'from-amber-600',
  'to-yellow-700',
  'text-amber-600',
  'bg-amber-100/20',
  'bg-yellow-100/10',
  '/course/blockchain-cryptocurrency',
  'published',
  23
);

-- Finally, let's add Pillar 3: Digital Skills & Modern Business
INSERT INTO courses (
  title, subtitle, modules, duration, diploma, feature1, feature2, icon, 
  gradient_from, gradient_to, button_text_color, floating_color1, floating_color2, 
  link_to, status, display_order
) VALUES 
-- AI-Powered Digital Marketing
(
  'AI-Powered Digital Marketing',
  'Marketing digital boosté par l''IA',
  '12 modules marketing',
  '5 mois',
  'Certificat AI Marketing Expert',
  'Automatisation marketing avec IA',
  'Personnalisation à grande échelle',
  'target',
  'from-pink-500',
  'to-rose-600',
  'text-pink-500',
  'bg-pink-100/20',
  'bg-rose-100/10',
  '/course/ai-powered-digital-marketing',
  'published',
  24
),
-- E-commerce Marketing
(
  'E-commerce Marketing',
  'Stratégies marketing pour e-commerce',
  '10 modules e-commerce',
  '4 mois',
  'Certificat E-commerce Marketing',
  'Conversion et optimisation',
  'Marketplaces et omnicanalité',
  'target',
  'from-violet-500',
  'to-purple-600',
  'text-violet-500',
  'bg-violet-100/20',
  'bg-purple-100/10',
  '/course/ecommerce-marketing',
  'published',
  25
),
-- Video Production & AI Editing
(
  'Video Production & AI Editing',
  'Production vidéo et montage assisté par IA',
  '9 modules vidéo',
  '4 mois',
  'Certificat Video Production AI',
  'Outils IA pour le montage',
  'Streaming et diffusion live',
  'code',
  'from-red-500',
  'to-pink-600',
  'text-red-500',
  'bg-red-100/20',
  'bg-pink-100/10',
  '/course/video-production-ai-editing',
  'published',
  26
),
-- Social Media Content Creation
(
  'Social Media Content Creation',
  'Création de contenu pour réseaux sociaux',
  '8 modules créatifs',
  '3 mois',
  'Certificat Social Media Creator',
  'Stratégies multi-plateformes',
  'Outils de création et automation',
  'target',
  'from-cyan-500',
  'to-teal-600',
  'text-cyan-500',
  'bg-cyan-100/20',
  'bg-teal-100/10',
  '/course/social-media-content-creation',
  'published',
  27
);
